### ISSUE TITLE
看了一下starter的网络请求内部实现，略微臃肿。

### ISSUE THREAD

**Issue by pc859107393** [tuya/tuya-connector#12]
看了一下你们http通信采用的技术栈是 retrofit+okhttp，整体设计的思路是很清晰的，分层设计也到位。最终也是实现的代理interface实现http调用。 个人建议更加简洁轻量的实现：okhttp+spring-core（注解扫描工具）实现基于代理interface的网络请求。

**Comment by yuqiufeng** [comment]
框架设计之初已经考虑到，所以抽象了ProxyDelegate，目前的实现是RetrofitDelegate是基于retrofit2，可以通过扩展自定义的ProxyDelegate来替换实现，欢迎进行PR，可以移步到：https://github.com/tuya/connector
