### ISSUE TITLE
与主流开发开发框架依赖存在冲突影响开发体验

### ISSUE THREAD

**Issue by q1763868326** [tuya/tuya-connector#14]
![微信截图_16310660351277](https://user-images.githubusercontent.com/42771347/132435024-0be635b5-d7c3-437f-8978-9bbfe5eda234.png)

![微信截图_1631066039198](https://user-images.githubusercontent.com/42771347/132434966-57591b36-9ac1-4a26-8e76-0d57fd9181a0.png)

**Comment by Edisonboy** [comment]
> ![微信截图_16310660351277](https://user-images.githubusercontent.com/42771347/132435024-0be635b5-d7c3-437f-8978-9bbfe5eda234.png)
> 
> ![微信截图_1631066039198](https://user-images.githubusercontent.com/42771347/132434966-57591b36-9ac1-4a26-8e76-0d57fd9181a0.png)

后续会补充相应的版本依赖~

**Comment by Edisonboy** [comment]
houxu
