### ISSUE TITLE
什么时候api 和消息队列能动态传入时区参数

### ISSUE THREAD

**Issue by realheyu** [tuya/tuya-connector#17]
如题

**Comment by realheyu** [comment]
现在只能在配置文件里配置静态的时区

**Comment by Edisonboy** [comment]
请问可以具体一下什么场景下需要动态设置时区呢

**Comment by yuqiufeng** [comment]
配置项里透出了region配置，支持访问对应区的接口，默认中国区
connector.region=CN

各区配置：
CN：中国区
US：美国区
EU：欧洲区
IN：印度区

**Comment by realheyu** [comment]
因为有几个时区的设备, 调用api的时候需要传入不同的时区, 现在是在配置文件中静态配置, 满足不了需求
