### ISSUE TITLE
tuya-spring-boot-starter-sample won't work due to baseUrl == null

### ISSUE THREAD

**Issue by jonasbark** [tuya/tuya-connector#21]
I cloned the latest sample (using 1.1.1) and ran it:

```
Caused by: java.lang.NullPointerException: baseUrl == null
	at java.base/java.util.Objects.requireNonNull(Objects.java:246) ~[na:na]
	at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:505) ~[retrofit-2.9.0.jar:na]
```
The only thing I changed is specifying the properties:
```
connector.ak=...
connector.sk=...
connector.region=EU
```

It works again when I specify this manually:
```
connector.api.base-url=https://openapi-weaz.tuyaeu.com
```

**Comment by Edisonboy** [comment]
Are you relying on the `tuya-spring-boot-starter` version  1.1.1 ?

**Comment by jonasbark** [comment]
Yes, but I've also tried 1.1.0 and 1.0.0 as well

**Comment by Edisonboy** [comment]
You can break points in `TuyaregionConfig` before debug program, check the method `afterPropertiesSet` whether it wrok.

**Comment by jonasbark** [comment]
I also did that - afterPropertiesSet is never called. Does it work for you?

**Comment by Edisonboy** [comment]
Oh, i found it doesn't work when i use the annotation `@EnbaleMessaging`. 
Sorry, we will fix it soon.

**Comment by Edisonboy** [comment]
> I also did that - afterPropertiesSet is never called. Does it work for you?

yes, it  worked. If you message can't connect correctly it doesn't work. So you need to check the configuration of message.

**Comment by Edisonboy** [comment]
> I also did that - afterPropertiesSet is never called. Does it work for you?

yes, it worked. If you message can't connect correctly it doesn't work. So you need to check the configuration of message.

**Comment by Edisonboy** [comment]
yes, it worked. If you message can't connect correctly it doesn't work. So you need to check the configuration of message.

**Comment by Edisonboy** [comment]
yes, it worked. If you message can't connect correctly it doesn't work. So you need to check the configuration of message.
