### ISSUE TITLE
Configuration bean  name  conflicted with  MyBatis Configuration bean

### ISSUE THREAD

**Issue by yuqiufeng** [tuya/tuya-connector#25]
![wecom-temp-e530fb814f5c35822a9f97abe8c03110](https://user-images.githubusercontent.com/17353158/147521183-45db28c2-9341-4a8e-bc0b-a9ffca833023.png)

suggest solution ： @ConditionalOnMissingBean  add Class type

**Comment by Edisonboy** [comment]
we had rename the bean name of Configuration at [1.1.3 version ](https://github.com/tuya/connector/commit/96a5612a358c478e31cad4999ddb1fdd0bdeda7a)
