### ISSUE TITLE
依赖问题

### ISSUE THREAD

**Issue by style0702** [tuya/tuya-connector#4]
依赖拉不下来

**Comment by zhoujiaping** [comment]
请问具体是哪些依赖拉不下来，能贴一下依赖的maven坐标吗？

**Comment by exception-coder** [comment]
tuya-spring-boot-starter

**Comment by Edisonboy** [comment]
Execute me, our dependency not deposit on central repository.
You need to add the following configuration on your project's pom.


<repository>
    <id>tuya-maven</id>
    <url>https://maven-other.tuya.com/repository/maven-public/</url>
</repository>

**Comment by Edisonboy** [comment]
我们的依赖包目前不是托管在maven中央仓库中的。可能需要您在maven 的setting 或者是项目的pom配置一下如下仓库信息：


<repository>
    <id>tuya-maven</id>
    <url>https://maven-other.tuya.com/repository/maven-public/</url>
</repository>

**Comment by Edisonboy** [comment]
我们的依赖包目前不是托管在maven中央仓库中的。
可能需要您在maven 的setting 或者是项目的pom配置一下如下仓库信息：
```xml
<!-- Specify the Maven repository URL -->
<repository>
    <id>tuya-maven</id>
    <url>https://maven-other.tuya.com/repository/maven-public/</url>
</repository>
```
